import "./globals.css";
import InteractiveBackground from "@/components/bg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <InteractiveBackground/>

        {children}
      </body>
    </html>
  );
}
